name: dish_connect

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.3.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  firebase_database: ^9.0.6
  firebase_storage: ^10.2.7
  flutter_easyloading: ^3.0.3
  firebase_crashlytics: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home_light.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf